spring.application.name=Car_Spare_Parts
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=CarSpareParts;trustServerCertificate=true;
spring.datasource.username=AppUser
spring.datasource.password=AppUser
spring.datasource.name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
