server.port=8082
spring.application.name=HW18.06.2025
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=Java411;trustServerCertificate=true;
spring.datasource.username=AppUser
spring.datasource.password=AppUser
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update