spring.application.name=JUnit
spring.datasource.username=AppUser
spring.datasource.password=AppUser
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=Java411;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=create
